version: '3'
services:
  redis:
    image: redis:latest 
  postgres:
    image: postgres:10.4
    environment:
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=app
  app:
    build: .
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=app
      - DB_PASSWORD=app
      - DB_HOST=postgres
      - REDIS_URL=redis://redis:6379/0
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - redis
      - postgres
    environment:
      - DB_USERNAME=app
      - DB_PASSWORD=app
      - DB_HOST=postgres
      - REDIS_URL=redis://redis:6379/0
